src/Entity/Articles.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticlesRepository")
 */
class Articles
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $Contents;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateInsert;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateUpdate;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $urlClean;

    /**
     * @ORM\Column(type="smallint", options={"default":0})
     */
    private $status;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $visible;    
    
    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="articles")
     */ 
    private $Category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $User;

    public function __construct()
    {
        $this->Category = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContents(): ?string
    {
        return $this->Contents;
    }

    public function setContents(string $Contents): self
    {
        $this->Contents = $Contents;

        return $this;
    }

    public function getDateInsert(): ?\DateTimeInterface
    {
        return $this->dateInsert;
    }

    public function setDateInsert(\DateTimeInterface $dateInsert): self
    {
        $this->dateInsert = $dateInsert;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeInterface
    {
        return $this->dateUpdate;
    }

    public function setDateUpdate(?\DateTimeInterface $dateUpdate): self
    {
        $this->dateUpdate = $dateUpdate;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategory(): Collection
    {
        return $this->Category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->Category->contains($category)) {
            $this->Category[] = $category;
            $category->setArticles($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->Category->contains($category)) {
            $this->Category->removeElement($category);
            // set the owning side to null (unless already changed)
            if ($category->getArticles() === $this) {
                $category->setArticles(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getUrlClean(): ?string
    {
        return $this->urlClean;
    }

    public function setUrlClean(string $urlClean): self
    {
        $this->urlClean = $urlClean;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(?bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }
}

src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Name;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $works;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $hackathon;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $formation;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Articles", mappedBy="Category")
     */
    private $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getArticles(): ?Articles
    {
        return $this->articles;
    }

    public function setArticles(?Articles $articles): self
    {
        $this->articles = $articles;

        return $this;
    }

    public function addArticle(Articles $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->addCategory($this);
        }

        return $this;
    }

    public function removeArticle(Articles $article): self
    {
        if ($this->articles->contains($article)) {
            $this->articles->removeElement($article);
            $article->removeCategory($this);
        }

        return $this;
    }

    public function getWorks(): ?bool
    {
        return $this->works;
    }

    public function setWorks(?bool $works): self
    {
        $this->works = $works;

        return $this;
    }

    public function getHackathon(): ?bool
    {
        return $this->hackathon;
    }

    public function setHackathon(?bool $hackathon): self
    {
        $this->hackathon = $hackathon;

        return $this;
    }

    public function getFormation(): ?bool
    {
        return $this->formation;
    }

    public function setFormation(?bool $formation): self
    {
        $this->formation = $formation;

        return $this;
    }

    public function __toString() 
    {
        return $this->getName();
    }
}

templates/Blogs/article.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="container">
    <h1>
        {{ article.title }}
    </h1>

    <p>
        {{ article.contents }}
    </p>

    <p>
        {% for category in article.category %}
            {{ category.name }}
        {% endfor %}
    </p>
    <p>
        écrit par {{ article.user.fullname }}
    </p>
</div>

{% endblock body %}

templates/Blogs/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}    
{% endblock body %}

templates/Blogs/create_success.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    success    
{% endblock body %}

templates/Blogs/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="d-flex">
            <div class="p-3 d-inline-block" style="background-color: #eee;">
                <img src="https://googlefr.i.lithium.com/html/assets/plp.png?F3F40606DF62B632BF4A233552B1BA55">
            </div>
            <div class="p-3 d-inline-block" style="background-color: #eee;">
                Phasellus quis consequat orci. Mauris in arcu nec arcu viverra luctus. Vestibulum orci felis, fringilla sit amet congue sit amet, dignissim eu lorem. Curabitur vel aliquet ex, et facilisis leo. Curabitur molestie quis massa at lobortis. Maecenas vel massa ac turpis auctor efficitur. In et ipsum eget erat venenatis tempus. Nam vel convallis felis, at sodales tellus. Vivamus vitae tellus ac neque gravida fringilla in non ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed aliquet, leo sit amet scelerisque venenatis, urna arcu fermentum leo, nec faucibus quam leo eu tellus.
            </div>
        </div>        
    </div>
    <div class="container">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d122561.05018662916!2d5.946057414188266!3d47.25096748020406!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x478d62faf0ee130b%3A0x409ce34b313ed30!2s25000+Besan%C3%A7on!5e0!3m2!1sfr!2sfr!4v1526107954616" width="100%" height="150" frameborder="0" style="border:0" allowfullscreen></iframe>        
    </div>
    <div class="container" style="margin-top: 1em;">
        <div class="p-3" style="background-color: #eee;">
            <b>Dernier article</b>
        </div>
        <div class="d-flex">
            <div class="p-3" style="background-color: #eee; width: 90%">
                Phasellus quis consequat orci. Mauris in arcu nec arcu viverra luctus. Vestibulum orci felis, fringilla sit amet congue sit amet, dignissim eu lorem. Curabitur vel aliquet ex, et facilisis leo. Curabitur molestie quis massa at lobortis. Maecenas vel massa ac turpis auctor efficitur. In et ipsum eget erat venenatis tempus. Nam vel convallis felis, at sodales tellus. Vivamus vitae tellus ac neque gravida fringilla in non ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed aliquet, leo sit amet scelerisque venenatis, urna arcu fermentum leo, nec faucibus quam leo eu tellus.
            </div>
            <div class="p-3" style="background-color: #eee; width: 10%; font-size: 3em;">
                <p class="text-center">
                    +
                </p>
            </div>
        </div>
    </div>

    <div class="container" style="margin-top: 1em;">
        <div class="p-3" style="background-color: #eee;">
            <b>Projets</b>
        </div>
        <div class="d-flex">
            <div class="p-3" style="background-color: #eee; width: 90%">
                <div class="d-flex">
                    <div class="w-50" style="background-color: #eee;">
                        <img src="https://googlefr.i.lithium.com/html/assets/plp.png?F3F40606DF62B632BF4A233552B1BA55">
                    </div>
                    <div class="w-50" style="background-color: #eee;">
                        <img src="https://googlefr.i.lithium.com/html/assets/plp.png?F3F40606DF62B632BF4A233552B1BA55">
                    </div>
                </div>
            </div>
            <div class="p-3" style="background-color: #eee; width: 10%; font-size: 3em;">
                <p class="text-center">
                    +
                </p>
            </div>
        </div>
    </div>
    <style>
        .portfolio-item .thumbnail{
            margin: 1em;
        }
    </style>
    <div class="container" style="margin-top: 1em;">
        <div class="p-3" style="background-color: #eee;">
            <b>Technologies</b>
        </div>
        <div class="d-flex">
            <div class="portfolio-item">
                <div class="thumbnail">
                    <img src="https://www.w3.org/html/logo/downloads/HTML5_Badge_512.png" width="70px" alt="...">
                </div>
            </div>
        
            <div class="portfolio-item">
                <div class="thumbnail">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/PHP-logo.svg/500px-PHP-logo.svg.png" width="70px" alt="...">
                </div>
            </div>
        
            <div class="portfolio-item">
                <div class="thumbnail">
                    <img src="http://verekia.com/_pages/css3/introduction-css3/img/css3-logo.png" width="70px" alt="...">
                </div>
            </div>
        
            <div class="portfolio-item">
                <div class="thumbnail">
                    <img src="http://www.tech-app.fr/wp-content/uploads/2015/04/9455413519_javascript.png" width="70px" alt="...">
                </div>
            </div>
        
            <div class="portfolio-item">
                <div class="thumbnail">
                    <img src="http://sass-lang.com/assets/img/logos/logo-b6e1ef6e.svg" width="70px" alt="...">
                </div>
            </div>
        
            <div class="portfolio-item">
                <div class="thumbnail">
                    <img src="http://www.loligrub.be/blog/wp-content/uploads/2017/01/docker_logo.png" width="70px" alt="...">
                </div>
            </div>
        
            <div class="portfolio-item">
                <div class="thumbnail">
                    <img src="http://precision-software.com/wp-content/uploads/2014/04/jQurery.gif" width="70px" alt="...">
                </div>
            </div>
        
            <div class="portfolio-item">
                <div class="thumbnail">
                    <img src="https://s1.wp.com/i/favicons/android-chrome-192x192.png" width="70px" alt="...">
                </div>
            </div>
        
            <div class="portfolio-item">
                <div class="thumbnail">
                    <img src="http://appadmin.sadadou.fr/bundles/sonataadmin/logo_title.png" width="70px" alt="...">
                </div>
            </div>
        
            <div class="portfolio-item">
                <div class="thumbnail">
                    <img src="https://symfony.com/images/v5/pictos/home-main-illu.svg" width="70px" alt="...">
                </div>
            </div>
        
            <div class="portfolio-item">
                <div class="thumbnail">
                    <img src="https://www.redfroggy.fr/wp-content/uploads/2016/03/2.png" width="70px" alt="...">
                </div>
            </div>
        </div>
    </div>
{% endblock body %}